### ISSUE TITLE
Develop Project Strategy

### ISSUE THREAD

**Issue by ghost** [joomla-projects/user-experience#6]

**Comment by artisandawn** [comment]
Organizational Diagram from JUX:

![20161112_152925 1](https://cloud.githubusercontent.com/assets/1074734/20242702/2c72358a-a8ed-11e6-8249-96a4be93ed0c.jpg)

**Comment by artisandawn** [comment]
Project "Dashboard" - UX team

![20161112_155331](https://cloud.githubusercontent.com/assets/1074734/20242805/bb2d741c-a8f0-11e6-8fb1-9ad98b0e415f.jpg)
